name: Beta Release (Linux Only)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0-beta.1)'
        required: true
        type: string

jobs:
  linux-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean up existing tag and release
        run: |
          # Delete existing tag locally and remotely
          git tag -d ${{ github.event.inputs.version }} 2>/dev/null || true
          git push origin --delete ${{ github.event.inputs.version }} 2>/dev/null || true
          
          # Delete existing GitHub release
          gh release delete ${{ github.event.inputs.version }} --yes 2>/dev/null || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install system dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y libnss3-dev libatk-bridge2.0-dev libdrm2 libxcomposite1 libxdamage1 libxrandr2 libgbm1 libxss1 libasound2-dev

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps --no-audit --no-fund
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Run tests (skip problematic ones)
        run: npm test -- --testPathIgnorePatterns="lokka-mcp-errors.test.ts"
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Build Linux application
        run: npm run build:electron:linux
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Create GitHub Release
        run: |
          gh release create ${{ github.event.inputs.version }} \
            --title "EntraPulse Lite ${{ github.event.inputs.version }} (Linux)" \
            --notes "Beta release of EntraPulse Lite for Linux." \
            --prerelease \
            dist-release/*.AppImage \
            dist-release/*.deb \
            dist-release/*.rpm \
            dist-release/*.tar.gz
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
