name: Beta Release (Windows Signed)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0-beta.1)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: true
        type: boolean

jobs:
  windows-signed-release:
    runs-on: windows-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci --legacy-peer-deps --no-audit --no-fund
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Run tests
        run: npm run test:ci
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Build and sign Windows application
        run: npm run build && npx electron-builder --win --publish=never
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ github.event.inputs.version }}
          name: ${{ github.event.inputs.version }}
          draft: false
          prerelease: ${{ github.event.inputs.prerelease == 'true' }}
          files: dist-release/*
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
