name: Beta Release (Signed)

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0-beta.1)'
        required: true
        type: string

jobs:
  windows-release:
    runs-on: windows-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Clean up existing tag and release
        run: |
          # Delete existing tag locally and remotely
          git tag -d ${{ github.event.inputs.version }} 2>/dev/null || true
          git push origin --delete ${{ github.event.inputs.version }} 2>/dev/null || true
          
          # Delete existing GitHub release
          gh release delete ${{ github.event.inputs.version }} --yes 2>/dev/null || true
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        continue-on-error: true

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: |
          npm ci --legacy-peer-deps --no-audit --no-fund
        env:
          NODE_OPTIONS: --max-old-space-size=8192

      - name: Run tests (skip problematic ones)
        run: npm run test:ci
        env:
          CI: true
          NODE_OPTIONS: --max-old-space-size=4096

      - name: Build application (signed)
        run: npm run build && electron-builder --publish=always
        env:
          NODE_OPTIONS: --max-old-space-size=8192
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}

      - name: Set release as prerelease
        run: |
          gh release edit ${{ github.event.inputs.version }} --prerelease
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
