name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0-beta.1)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: true
        type: boolean

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Validate version format
        run: |
          if [[ ! "${{ github.event.inputs.version }}" =~ ^v[0-9]+\.[0-9]+\.[0-9]+(-[a-zA-Z0-9.-]+)?$ ]]; then
            echo "Invalid version format. Expected: v1.0.0 or v1.0.0-beta.1"
            exit 1
          fi

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          
          # Check if tag already exists
          if git rev-parse "${{ github.event.inputs.version }}" >/dev/null 2>&1; then
            echo "Tag ${{ github.event.inputs.version }} already exists. Deleting and recreating..."
            git tag -d "${{ github.event.inputs.version }}" || true
            git push origin :refs/tags/${{ github.event.inputs.version }} || true
          fi
          
          # Delete existing GitHub release if it exists
          gh release delete "${{ github.event.inputs.version }}" --yes --cleanup-tag || true
          
          # Create new tag
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-and-release:
    needs: create-release
    runs-on: windows-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}
          fetch-depth: 0

      - name: Setup Windows build environment
        if: runner.os == 'Windows'
        run: |
          # Set up Windows-specific environment
          $env:ELECTRON_CACHE = "$env:USERPROFILE\.cache\electron"
          $env:ELECTRON_BUILDER_CACHE = "$env:USERPROFILE\.cache\electron-builder"
          echo "ELECTRON_CACHE=$env:ELECTRON_CACHE" >> $env:GITHUB_ENV
          echo "ELECTRON_BUILDER_CACHE=$env:ELECTRON_BUILDER_CACHE" >> $env:GITHUB_ENV

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Clean npm cache
        run: npm cache clean --force

      - name: Install dependencies
        run: |
          npm ci --no-audit --no-fund --legacy-peer-deps
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"

      - name: Run tests
        run: npm run test:ci
        env:
          NODE_OPTIONS: "--max-old-space-size=4096"
          CI: true

      - name: Run security checks
        run: npm run security:check

      - name: Update version in source files
        run: |
          # Update package.json
          npm version --no-git-tag-version ${{ github.event.inputs.version }}
          
          # Update version.ts (remove 'v' prefix for source file)
          $VERSION_NO_V = "${{ github.event.inputs.version }}" -replace "^v", ""
          
          # Update src/shared/version.ts
          if (Test-Path "src/shared/version.ts") {
            $content = Get-Content "src/shared/version.ts"
            $content = $content -replace "export const VERSION = .*", "export const VERSION = '$VERSION_NO_V';"
            $content | Set-Content "src/shared/version.ts"
          }

      - name: Set prerelease flag
        if: ${{ github.event.inputs.prerelease == 'true' }}
        run: |
          node -e "
            const pkg = require('./package.json');
            if (!pkg.build) pkg.build = {};
            if (!pkg.build.publish) pkg.build.publish = {};
            pkg.build.publish.releaseType = 'prerelease';
            require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n');
          "

      - name: Set release flag
        if: ${{ github.event.inputs.prerelease != 'true' }}
        run: |
          node -e "
            const pkg = require('./package.json');
            if (!pkg.build) pkg.build = {};
            if (!pkg.build.publish) pkg.build.publish = {};
            pkg.build.publish.releaseType = 'release';
            require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n');
          "

      - name: Verify configuration
        run: |
          echo "Package version: $(node -p "require('./package.json').version")"
          echo "Release type: $(node -p "require('./package.json').build?.publish?.releaseType || 'undefined'")"
          echo "Prerelease input: ${{ github.event.inputs.prerelease }}"
          
          # Verify version.ts was updated
          if (Test-Path "src/shared/version.ts") {
            Write-Host "Version.ts content:"
            Get-Content "src/shared/version.ts"
          }

      - name: Build and release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          WIN_CSC_LINK: ${{ secrets.WIN_CSC_LINK }}
          WIN_CSC_KEY_PASSWORD: ${{ secrets.WIN_CSC_KEY_PASSWORD }}
          NODE_OPTIONS: "--max-old-space-size=8192"
          
      - name: Upload build artifacts (on failure)
        if: failure()
        uses: actions/upload-artifact@v4
        with:
          name: build-logs-windows-${{ github.run_number }}
          path: |
            dist/
            dist-release/
            *.log
            npm-debug.log*
            .npm/_logs/