name: Manual Release

on:
  workflow_dispatch:
    inputs:
      version:
        description: 'Release version (e.g., v1.0.0-beta.1)'
        required: true
        type: string
      prerelease:
        description: 'Mark as pre-release'
        required: false
        default: true
        type: boolean

jobs:
  create-release:
    runs-on: ubuntu-latest
    
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4

      - name: Create and push tag
        run: |
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git tag ${{ github.event.inputs.version }}
          git push origin ${{ github.event.inputs.version }}

  build-and-release:
    needs: create-release
    runs-on: ${{ matrix.os }}
    
    strategy:
      matrix:
        os: [windows-latest, macos-latest, ubuntu-latest]

    steps:
      - name: Check out Git repository
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.inputs.version }}

      - name: Install Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Run tests
        run: npm test

      - name: Run security checks
        run: npm run security:check

      - name: Update package.json version
        run: |
          npm version --no-git-tag-version ${{ github.event.inputs.version }}

      - name: Set prerelease flag
        if: ${{ github.event.inputs.prerelease == 'true' }}
        run: |
          node -e "
            const pkg = require('./package.json');
            pkg.build.publish.releaseType = 'prerelease';
            require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n');
          "

      - name: Set release flag
        if: ${{ github.event.inputs.prerelease != 'true' }}
        run: |
          node -e "
            const pkg = require('./package.json');
            pkg.build.publish.releaseType = 'release';
            require('fs').writeFileSync('./package.json', JSON.stringify(pkg, null, 2) + '\n');
          "

      - name: Verify configuration
        run: |
          echo "Package version: $(node -p "require('./package.json').version")"
          echo "Release type: $(node -p "require('./package.json').build.publish.releaseType")"
          echo "Prerelease input: ${{ github.event.inputs.prerelease }}"

      - name: Build and release
        run: npm run release
        env:
          GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          CSC_NAME: "Darren J Robinson"
          WIN_CSC_IDENTITY_AUTO_DISCOVERY: true